/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttendanceRecord {
  'studentId' : bigint,
  'isPresent' : boolean,
  'date' : string,
}
export interface FeeRecord {
  'month' : string,
  'paymentStatus' : PaymentStatus,
  'studentId' : bigint,
  'classesConducted' : bigint,
  'dueDate' : string,
  'classesAttended' : bigint,
  'paidAmount' : bigint,
}
export type PaymentStatus = { 'Paid' : null } |
  { 'Pending' : null };
export interface Settings { 'instituteName' : string }
export interface Student {
  'id' : bigint,
  'name' : string,
  'batch' : string,
  'contactNumber' : string,
  'monthlyFee' : bigint,
  'className' : string,
}
export interface TopicLog {
  'id' : bigint,
  'topic' : string,
  'studentId' : bigint,
  'date' : string,
  'notes' : [] | [string],
}
export interface _SERVICE {
  'addStudent' : ActorMethod<[Student], bigint>,
  'addTopicLog' : ActorMethod<[TopicLog], bigint>,
  'deleteStudent' : ActorMethod<[bigint], undefined>,
  'getAllStudents' : ActorMethod<[], Array<Student>>,
  'getAttendance' : ActorMethod<[bigint, string], AttendanceRecord>,
  'getFeeRecord' : ActorMethod<[bigint, string], FeeRecord>,
  'getPendingFeesForMonth' : ActorMethod<[string], Array<FeeRecord>>,
  'getSettings' : ActorMethod<[], Settings>,
  'getStudent' : ActorMethod<[bigint], Student>,
  'getTopicLog' : ActorMethod<[bigint], TopicLog>,
  'getTotalIncomeForMonth' : ActorMethod<[string], bigint>,
  'markAttendance' : ActorMethod<[AttendanceRecord], undefined>,
  'updateSettings' : ActorMethod<[Settings], undefined>,
  'updateStudent' : ActorMethod<[bigint, Student], undefined>,
  'updateTopicLog' : ActorMethod<[bigint, TopicLog], undefined>,
  'upsertFeeRecord' : ActorMethod<[FeeRecord], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];