/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Student = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'batch' : IDL.Text,
  'contactNumber' : IDL.Text,
  'monthlyFee' : IDL.Nat,
  'className' : IDL.Text,
});
export const TopicLog = IDL.Record({
  'id' : IDL.Nat,
  'topic' : IDL.Text,
  'studentId' : IDL.Nat,
  'date' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
});
export const AttendanceRecord = IDL.Record({
  'studentId' : IDL.Nat,
  'isPresent' : IDL.Bool,
  'date' : IDL.Text,
});
export const PaymentStatus = IDL.Variant({
  'Paid' : IDL.Null,
  'Pending' : IDL.Null,
});
export const FeeRecord = IDL.Record({
  'month' : IDL.Text,
  'paymentStatus' : PaymentStatus,
  'studentId' : IDL.Nat,
  'classesConducted' : IDL.Nat,
  'dueDate' : IDL.Text,
  'classesAttended' : IDL.Nat,
  'paidAmount' : IDL.Nat,
});
export const Settings = IDL.Record({ 'instituteName' : IDL.Text });

export const idlService = IDL.Service({
  'addStudent' : IDL.Func([Student], [IDL.Nat], []),
  'addTopicLog' : IDL.Func([TopicLog], [IDL.Nat], []),
  'deleteStudent' : IDL.Func([IDL.Nat], [], []),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getAttendance' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [AttendanceRecord],
      ['query'],
    ),
  'getFeeRecord' : IDL.Func([IDL.Nat, IDL.Text], [FeeRecord], ['query']),
  'getPendingFeesForMonth' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(FeeRecord)],
      ['query'],
    ),
  'getSettings' : IDL.Func([], [Settings], ['query']),
  'getStudent' : IDL.Func([IDL.Nat], [Student], ['query']),
  'getTopicLog' : IDL.Func([IDL.Nat], [TopicLog], ['query']),
  'getTotalIncomeForMonth' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'markAttendance' : IDL.Func([AttendanceRecord], [], []),
  'updateSettings' : IDL.Func([Settings], [], []),
  'updateStudent' : IDL.Func([IDL.Nat, Student], [], []),
  'updateTopicLog' : IDL.Func([IDL.Nat, TopicLog], [], []),
  'upsertFeeRecord' : IDL.Func([FeeRecord], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Student = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'batch' : IDL.Text,
    'contactNumber' : IDL.Text,
    'monthlyFee' : IDL.Nat,
    'className' : IDL.Text,
  });
  const TopicLog = IDL.Record({
    'id' : IDL.Nat,
    'topic' : IDL.Text,
    'studentId' : IDL.Nat,
    'date' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
  });
  const AttendanceRecord = IDL.Record({
    'studentId' : IDL.Nat,
    'isPresent' : IDL.Bool,
    'date' : IDL.Text,
  });
  const PaymentStatus = IDL.Variant({
    'Paid' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const FeeRecord = IDL.Record({
    'month' : IDL.Text,
    'paymentStatus' : PaymentStatus,
    'studentId' : IDL.Nat,
    'classesConducted' : IDL.Nat,
    'dueDate' : IDL.Text,
    'classesAttended' : IDL.Nat,
    'paidAmount' : IDL.Nat,
  });
  const Settings = IDL.Record({ 'instituteName' : IDL.Text });
  
  return IDL.Service({
    'addStudent' : IDL.Func([Student], [IDL.Nat], []),
    'addTopicLog' : IDL.Func([TopicLog], [IDL.Nat], []),
    'deleteStudent' : IDL.Func([IDL.Nat], [], []),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getAttendance' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [AttendanceRecord],
        ['query'],
      ),
    'getFeeRecord' : IDL.Func([IDL.Nat, IDL.Text], [FeeRecord], ['query']),
    'getPendingFeesForMonth' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FeeRecord)],
        ['query'],
      ),
    'getSettings' : IDL.Func([], [Settings], ['query']),
    'getStudent' : IDL.Func([IDL.Nat], [Student], ['query']),
    'getTopicLog' : IDL.Func([IDL.Nat], [TopicLog], ['query']),
    'getTotalIncomeForMonth' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'markAttendance' : IDL.Func([AttendanceRecord], [], []),
    'updateSettings' : IDL.Func([Settings], [], []),
    'updateStudent' : IDL.Func([IDL.Nat, Student], [], []),
    'updateTopicLog' : IDL.Func([IDL.Nat, TopicLog], [], []),
    'upsertFeeRecord' : IDL.Func([FeeRecord], [], []),
  });
};

export const init = ({ IDL }) => { return []; };