/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Settings {
    instituteName: string;
    logoData?: string;
}
export interface FeeRecord {
    month: string;
    paymentStatus: PaymentStatus;
    studentId: bigint;
    classesConducted: bigint;
    dueDate: string;
    classesAttended: bigint;
    paidAmount: bigint;
}
export interface AttendanceRecord {
    studentId: bigint;
    isPresent: boolean;
    date: string;
}
export interface TopicLog {
    id: bigint;
    topic: string;
    studentId: bigint;
    date: string;
    notes?: string;
}
export interface Student {
    id: bigint;
    name: string;
    academicSession: string;
    batch: string;
    contactNumber: string;
    monthlyFee: bigint;
    className: string;
}
export enum PaymentStatus {
    Paid = "Paid",
    Pending = "Pending"
}
export interface backendInterface {
    addStudent(student: Student): Promise<bigint>;
    addTopicLog(log: TopicLog): Promise<bigint>;
    deleteStudent(id: bigint): Promise<void>;
    getAllFeeRecords(): Promise<Array<FeeRecord>>;
    getAllStudents(): Promise<Array<Student>>;
    getAttendance(studentId: bigint, date: string): Promise<AttendanceRecord>;
    getFeeRecord(studentId: bigint, month: string): Promise<FeeRecord>;
    getPendingFeesForMonth(month: string): Promise<Array<FeeRecord>>;
    getSettings(): Promise<Settings>;
    getStudent(id: bigint): Promise<Student>;
    getTopicLog(id: bigint): Promise<TopicLog>;
    getTotalIncomeForMonth(month: string): Promise<bigint>;
    markAttendance(record: AttendanceRecord): Promise<void>;
    updateSettings(newSettings: Settings): Promise<void>;
    updateStudent(id: bigint, student: Student): Promise<void>;
    updateTopicLog(id: bigint, log: TopicLog): Promise<void>;
    upsertFeeRecord(record: FeeRecord): Promise<void>;
}
import type { FeeRecord as _FeeRecord, PaymentStatus as _PaymentStatus, TopicLog as _TopicLog } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addStudent(arg0: Student): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStudent(arg0);
            return result;
        }
    }
    async addTopicLog(arg0: TopicLog): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTopicLog(to_candid_TopicLog_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTopicLog(to_candid_TopicLog_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteStudent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudent(arg0);
            return result;
        }
    }
    async getAllFeeRecords(): Promise<Array<FeeRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFeeRecords();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFeeRecords();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllStudents(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudents();
            return result;
        }
    }
    async getAttendance(arg0: bigint, arg1: string): Promise<AttendanceRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendance(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendance(arg0, arg1);
            return result;
        }
    }
    async getFeeRecord(arg0: bigint, arg1: string): Promise<FeeRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeeRecord(arg0, arg1);
                return from_candid_FeeRecord_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeeRecord(arg0, arg1);
            return from_candid_FeeRecord_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingFeesForMonth(arg0: string): Promise<Array<FeeRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingFeesForMonth(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingFeesForMonth(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSettings(): Promise<Settings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return { instituteName: result.instituteName, logoData: result.logoData.length > 0 ? result.logoData[0] : undefined };
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return { instituteName: result.instituteName, logoData: result.logoData.length > 0 ? result.logoData[0] : undefined };
        }
    }
    async getStudent(arg0: bigint): Promise<Student> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudent(arg0);
            return result;
        }
    }
    async getTopicLog(arg0: bigint): Promise<TopicLog> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopicLog(arg0);
                return from_candid_TopicLog_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopicLog(arg0);
            return from_candid_TopicLog_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalIncomeForMonth(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalIncomeForMonth(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalIncomeForMonth(arg0);
            return result;
        }
    }
    async markAttendance(arg0: AttendanceRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAttendance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAttendance(arg0);
            return result;
        }
    }
    async updateSettings(arg0: Settings): Promise<void> {
        const candid_arg0 = { instituteName: arg0.instituteName, logoData: arg0.logoData ? [arg0.logoData] : [] };
        if (this.processError) {
            try {
                const result = await this.actor.updateSettings(candid_arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSettings(candid_arg0);
            return result;
        }
    }
    async updateStudent(arg0: bigint, arg1: Student): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudent(arg0, arg1);
            return result;
        }
    }
    async updateTopicLog(arg0: bigint, arg1: TopicLog): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTopicLog(arg0, to_candid_TopicLog_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTopicLog(arg0, to_candid_TopicLog_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async upsertFeeRecord(arg0: FeeRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertFeeRecord(to_candid_FeeRecord_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertFeeRecord(to_candid_FeeRecord_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_FeeRecord_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeeRecord): FeeRecord {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_TopicLog_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TopicLog): TopicLog {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    month: string;
    paymentStatus: _PaymentStatus;
    studentId: bigint;
    classesConducted: bigint;
    dueDate: string;
    classesAttended: bigint;
    paidAmount: bigint;
}): {
    month: string;
    paymentStatus: PaymentStatus;
    studentId: bigint;
    classesConducted: bigint;
    dueDate: string;
    classesAttended: bigint;
    paidAmount: bigint;
} {
    return {
        month: value.month,
        paymentStatus: from_candid_PaymentStatus_n5(_uploadFile, _downloadFile, value.paymentStatus),
        studentId: value.studentId,
        classesConducted: value.classesConducted,
        dueDate: value.dueDate,
        classesAttended: value.classesAttended,
        paidAmount: value.paidAmount
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    topic: string;
    studentId: bigint;
    date: string;
    notes: [] | [string];
}): {
    id: bigint;
    topic: string;
    studentId: bigint;
    date: string;
    notes?: string;
} {
    return {
        id: value.id,
        topic: value.topic,
        studentId: value.studentId,
        date: value.date,
        notes: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.notes))
    };
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Paid: null;
} | {
    Pending: null;
}): PaymentStatus {
    return "Paid" in value ? PaymentStatus.Paid : "Pending" in value ? PaymentStatus.Pending : value;
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FeeRecord>): Array<FeeRecord> {
    return value.map((x)=>from_candid_FeeRecord_n3(_uploadFile, _downloadFile, x));
}
function to_candid_FeeRecord_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FeeRecord): _FeeRecord {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): _PaymentStatus {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_TopicLog_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TopicLog): _TopicLog {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    month: string;
    paymentStatus: PaymentStatus;
    studentId: bigint;
    classesConducted: bigint;
    dueDate: string;
    classesAttended: bigint;
    paidAmount: bigint;
}): {
    month: string;
    paymentStatus: _PaymentStatus;
    studentId: bigint;
    classesConducted: bigint;
    dueDate: string;
    classesAttended: bigint;
    paidAmount: bigint;
} {
    return {
        month: value.month,
        paymentStatus: to_candid_PaymentStatus_n13(_uploadFile, _downloadFile, value.paymentStatus),
        studentId: value.studentId,
        classesConducted: value.classesConducted,
        dueDate: value.dueDate,
        classesAttended: value.classesAttended,
        paidAmount: value.paidAmount
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    topic: string;
    studentId: bigint;
    date: string;
    notes?: string;
}): {
    id: bigint;
    topic: string;
    studentId: bigint;
    date: string;
    notes: [] | [string];
} {
    return {
        id: value.id,
        topic: value.topic,
        studentId: value.studentId,
        date: value.date,
        notes: value.notes ? candid_some(value.notes) : candid_none()
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): {
    Paid: null;
} | {
    Pending: null;
} {
    return value == PaymentStatus.Paid ? {
        Paid: null
    } : value == PaymentStatus.Pending ? {
        Pending: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
